### ISSUE TITLE
Import doesnt work in python3.7, only for python2.7

### ISSUE THREAD

**Issue by el-hult** [shergreen/pyppca#1]
Hi,

I got super happy when I found this repo. Unfortunately,  the library doesnt work with Python3.7. The result I get is as below:

```
pip install pyppca
python
>>>  from pyppca import ppca
ImportError: cannot import name 'ppca' from 'pyppca' (C:\Users\{username}\Anaconda3\lib\site-packages\pyppca\__init__.py)
```

Switching to an environment with python 2.7 makes it work perfect. I guess you must update the __init__.py files to allow python 3 imports. Alternatively, update setup.py and add a disclaimer in README that you are not supporting python3.

**Comment by shergreen** [comment]
Fixed. Should now work in both python 2 and 3. Download version 0.0.4 from pip and you should be able to import the function using `from pyppca import ppca`
